/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: mfb64 (https://sketchfab.com/mfb64)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/vinyls-1-159fbaa320324c98af849a49eeae2461
title: VINYLS 1
*/

import React, { useRef } from 'react';
import { useGLTF } from '@react-three/drei';
import { useFrame } from '@react-three/fiber';

export function Vinyls(props) {
  const meshRef = useRef(null);
  useFrame(() => (meshRef.current.rotation.z += 0.003));
  const { nodes, materials } = useGLTF('/vinyls.gltf');
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <group
            position={[-0.13, 0.16, -0.34]}
            rotation={[Math.PI / 2, 0, -Math.PI / 2]}
          >
            <mesh
              ref={meshRef}
              geometry={nodes.Object_4.geometry}
              material={materials['cover.001']}
            />
            <mesh
              ref={meshRef}
              geometry={nodes.Object_5.geometry}
              material={materials.cardboard}
            />
          </group>
          <group
            position={[-0.11, 0.16, -0.33]}
            rotation={[Math.PI / 2, 0.04, -Math.PI / 2]}
          >
            <mesh
              ref={meshRef}
              geometry={nodes.Object_7.geometry}
              material={materials['cover.002']}
            />
            <mesh
              ref={meshRef}
              geometry={nodes.Object_8.geometry}
              material={materials.cardboard}
            />
          </group>
          <group
            position={[-0.07, 0.16, -0.33]}
            rotation={[Math.PI / 2, 0, -Math.PI / 2]}
          >
            <mesh
              ref={meshRef}
              geometry={nodes.Object_10.geometry}
              material={materials['cover.003']}
            />
            <mesh
              ref={meshRef}
              geometry={nodes.Object_11.geometry}
              material={materials.cardboard}
            />
          </group>
          <group
            position={[-0.04, 0.16, -0.33]}
            rotation={[Math.PI / 2, 0.03, -Math.PI / 2]}
          >
            <mesh
              ref={meshRef}
              geometry={nodes.Object_13.geometry}
              material={materials['cover.004']}
            />
            <mesh
              ref={meshRef}
              geometry={nodes.Object_14.geometry}
              material={materials.cardboard}
            />
          </group>
          <group
            position={[-0.01, 0.16, -0.31]}
            rotation={[Math.PI / 2, 0, -Math.PI / 2]}
          >
            <mesh
              ref={meshRef}
              geometry={nodes.Object_16.geometry}
              material={materials['cover.005']}
            />
            <mesh
              ref={meshRef}
              geometry={nodes.Object_17.geometry}
              material={materials.cardboard}
            />
          </group>
          <group
            position={[0.02, 0.16, -0.33]}
            rotation={[Math.PI / 2, 0, -Math.PI / 2]}
          >
            <mesh
              ref={meshRef}
              geometry={nodes.Object_19.geometry}
              material={materials['cover.006']}
            />
            <mesh
              ref={meshRef}
              geometry={nodes.Object_20.geometry}
              material={materials.cardboard}
            />
          </group>
          <group
            position={[0.05, 0.16, -0.34]}
            rotation={[Math.PI / 2, 0.02, -Math.PI / 2]}
          >
            <mesh
              ref={meshRef}
              geometry={nodes.Object_22.geometry}
              material={materials['cover.007']}
            />
            <mesh
              ref={meshRef}
              geometry={nodes.Object_23.geometry}
              material={materials.cardboard}
            />
          </group>
          <group
            position={[0.08, 0.16, -0.34]}
            rotation={[Math.PI / 2, 0.03, -Math.PI / 2]}
          >
            <mesh
              ref={meshRef}
              geometry={nodes.Object_25.geometry}
              material={materials['cover.008']}
            />
            <mesh
              ref={meshRef}
              geometry={nodes.Object_26.geometry}
              material={materials.cardboard}
            />
          </group>
          <group
            position={[0.11, 0.16, -0.33]}
            rotation={[Math.PI / 2, 0, -Math.PI / 2]}
          >
            <mesh
              ref={meshRef}
              geometry={nodes.Object_28.geometry}
              material={materials['cover.009']}
            />
            <mesh
              ref={meshRef}
              geometry={nodes.Object_29.geometry}
              material={materials.cardboard}
            />
          </group>
          <group
            position={[0.15, 0.16, -0.33]}
            rotation={[Math.PI / 2, 0.11, -Math.PI / 2]}
          >
            <mesh
              ref={meshRef}
              geometry={nodes.Object_31.geometry}
              material={materials['cover.010']}
            />
            <mesh
              ref={meshRef}
              geometry={nodes.Object_32.geometry}
              material={materials.cardboard}
            />
          </group>
          <group
            position={[-0.14, 0.16, -0.34]}
            rotation={[Math.PI / 2, 0.02, -Math.PI / 2]}
          >
            <mesh
              ref={meshRef}
              geometry={nodes.Object_34.geometry}
              material={materials['cover.011']}
            />
            <mesh
              ref={meshRef}
              geometry={nodes.Object_35.geometry}
              material={materials.cardboard}
            />
          </group>
          <group
            position={[-0.11, 0.16, -0.33]}
            rotation={[Math.PI / 2, 0.03, -Math.PI / 2]}
          >
            <mesh
              ref={meshRef}
              geometry={nodes.Object_37.geometry}
              material={materials['cover.012']}
            />
            <mesh
              ref={meshRef}
              geometry={nodes.Object_38.geometry}
              material={materials.cardboard}
            />
          </group>
          <group
            position={[-0.07, 0.16, -0.33]}
            rotation={[Math.PI / 2, 0, -Math.PI / 2]}
          >
            <mesh
              ref={meshRef}
              geometry={nodes.Object_40.geometry}
              material={materials['cover.013']}
            />
            <mesh
              ref={meshRef}
              geometry={nodes.Object_41.geometry}
              material={materials.cardboard}
            />
          </group>
          <group
            position={[-0.05, 0.16, -0.28]}
            rotation={[Math.PI / 2, 0, -Math.PI / 2]}
          >
            <mesh
              ref={meshRef}
              geometry={nodes.Object_43.geometry}
              material={materials['cover.014']}
            />
            <mesh
              ref={meshRef}
              geometry={nodes.Object_44.geometry}
              material={materials.cardboard}
            />
          </group>
          <group
            position={[-0.02, 0.16, -0.34]}
            rotation={[Math.PI / 2, 0.01, -Math.PI / 2]}
          >
            <mesh
              ref={meshRef}
              geometry={nodes.Object_46.geometry}
              material={materials['cover.015']}
            />
            <mesh
              ref={meshRef}
              geometry={nodes.Object_47.geometry}
              material={materials.cardboard}
            />
          </group>
          <group
            position={[0.01, 0.16, -0.34]}
            rotation={[Math.PI / 2, 0, -Math.PI / 2]}
          >
            <mesh
              ref={meshRef}
              geometry={nodes.Object_49.geometry}
              material={materials['cover.016']}
            />
            <mesh
              ref={meshRef}
              geometry={nodes.Object_50.geometry}
              material={materials.cardboard}
            />
          </group>
          <group
            position={[0.04, 0.16, -0.33]}
            rotation={[Math.PI / 2, 0.03, -Math.PI / 2]}
          >
            <mesh
              ref={meshRef}
              geometry={nodes.Object_52.geometry}
              material={materials['cover.017']}
            />
            <mesh
              ref={meshRef}
              geometry={nodes.Object_53.geometry}
              material={materials.cardboard}
            />
          </group>
          <group
            position={[0.07, 0.16, -0.33]}
            rotation={[Math.PI / 2, 0.04, -Math.PI / 2]}
          >
            <mesh
              ref={meshRef}
              geometry={nodes.Object_55.geometry}
              material={materials['cover.018']}
            />
            <mesh
              ref={meshRef}
              geometry={nodes.Object_56.geometry}
              material={materials.cardboard}
            />
          </group>
          <group
            position={[0.1, 0.16, -0.34]}
            rotation={[Math.PI / 2, 0, -Math.PI / 2]}
          >
            <mesh
              ref={meshRef}
              geometry={nodes.Object_58.geometry}
              material={materials['cover.019']}
            />
            <mesh
              ref={meshRef}
              geometry={nodes.Object_59.geometry}
              material={materials.cardboard}
            />
          </group>
          <group
            position={[0.14, 0.16, -0.33]}
            rotation={[Math.PI / 2, 0.07, -Math.PI / 2]}
          >
            <mesh
              ref={meshRef}
              geometry={nodes.Object_61.geometry}
              material={materials['cover.020']}
            />
            <mesh
              ref={meshRef}
              geometry={nodes.Object_62.geometry}
              material={materials.cardboard}
            />
          </group>
          <group
            position={[-0.14, 0.16, -0.34]}
            rotation={[Math.PI / 2, 0.03, -Math.PI / 2]}
          >
            <mesh
              ref={meshRef}
              geometry={nodes.Object_64.geometry}
              material={materials['cover.021']}
            />
            <mesh
              ref={meshRef}
              geometry={nodes.Object_65.geometry}
              material={materials.cardboard}
            />
          </group>
          <group
            position={[-0.12, 0.16, -0.33]}
            rotation={[Math.PI / 2, 0.02, -Math.PI / 2]}
          >
            <mesh
              ref={meshRef}
              geometry={nodes.Object_67.geometry}
              material={materials['cover.022']}
            />
            <mesh
              ref={meshRef}
              geometry={nodes.Object_68.geometry}
              material={materials.cardboard}
            />
          </group>
          <group
            position={[-0.09, 0.16, -0.33]}
            rotation={[Math.PI / 2, 0.07, -Math.PI / 2]}
          >
            <mesh
              ref={meshRef}
              geometry={nodes.Object_70.geometry}
              material={materials['cover.023']}
            />
            <mesh
              ref={meshRef}
              geometry={nodes.Object_71.geometry}
              material={materials.cardboard}
            />
          </group>
          <group
            position={[-0.05, 0.16, -0.33]}
            rotation={[Math.PI / 2, 0, -Math.PI / 2]}
          >
            <mesh
              ref={meshRef}
              geometry={nodes.Object_73.geometry}
              material={materials['cover.024']}
            />
            <mesh
              ref={meshRef}
              geometry={nodes.Object_74.geometry}
              material={materials.cardboard}
            />
          </group>
          <group
            position={[-0.02, 0.16, -0.33]}
            rotation={[Math.PI / 2, 0, -Math.PI / 2]}
          >
            <mesh
              ref={meshRef}
              geometry={nodes.Object_76.geometry}
              material={materials['cover.025']}
            />
            <mesh
              ref={meshRef}
              geometry={nodes.Object_77.geometry}
              material={materials.cardboard}
            />
          </group>
          <group
            position={[0.01, 0.16, -0.33]}
            rotation={[Math.PI / 2, 0, -Math.PI / 2]}
          >
            <mesh
              ref={meshRef}
              geometry={nodes.Object_79.geometry}
              material={materials['cover.026']}
            />
            <mesh
              ref={meshRef}
              geometry={nodes.Object_80.geometry}
              material={materials.cardboard}
            />
          </group>
          <group
            position={[0.04, 0.16, -0.34]}
            rotation={[Math.PI / 2, 0, -Math.PI / 2]}
          >
            <mesh
              ref={meshRef}
              geometry={nodes.Object_82.geometry}
              material={materials['cover.027']}
            />
            <mesh
              ref={meshRef}
              geometry={nodes.Object_83.geometry}
              material={materials.cardboard}
            />
          </group>
          <group
            position={[0.06, 0.16, -0.34]}
            rotation={[Math.PI / 2, 0, -Math.PI / 2]}
          >
            <mesh
              ref={meshRef}
              geometry={nodes.Object_85.geometry}
              material={materials['cover.028']}
            />
            <mesh
              ref={meshRef}
              geometry={nodes.Object_86.geometry}
              material={materials.cardboard}
            />
          </group>
          <group
            position={[0.1, 0.16, -0.34]}
            rotation={[Math.PI / 2, 0, -Math.PI / 2]}
          >
            <mesh
              ref={meshRef}
              geometry={nodes.Object_88.geometry}
              material={materials['cover.029']}
            />
            <mesh
              ref={meshRef}
              geometry={nodes.Object_89.geometry}
              material={materials.cardboard}
            />
          </group>
          <group
            position={[0.13, 0.16, -0.33]}
            rotation={[Math.PI / 2, 0, -Math.PI / 2]}
          >
            <mesh
              ref={meshRef}
              geometry={nodes.Object_91.geometry}
              material={materials['cover.030']}
            />
            <mesh
              ref={meshRef}
              geometry={nodes.Object_92.geometry}
              material={materials.cardboard}
            />
          </group>
          <group
            position={[-0.14, 0.16, -0.34]}
            rotation={[Math.PI / 2, 0.03, -Math.PI / 2]}
          >
            <mesh
              ref={meshRef}
              geometry={nodes.Object_94.geometry}
              material={materials['cover.031']}
            />
            <mesh
              ref={meshRef}
              geometry={nodes.Object_95.geometry}
              material={materials.cardboard}
            />
          </group>
          <group
            position={[-0.12, 0.16, -0.33]}
            rotation={[Math.PI / 2, 0.01, -Math.PI / 2]}
          >
            <mesh
              ref={meshRef}
              geometry={nodes.Object_97.geometry}
              material={materials['cover.032']}
            />
            <mesh
              ref={meshRef}
              geometry={nodes.Object_98.geometry}
              material={materials.cardboard}
            />
          </group>
          <group
            position={[-0.1, 0.16, -0.33]}
            rotation={[Math.PI / 2, 0.05, -Math.PI / 2]}
          >
            <mesh
              ref={meshRef}
              geometry={nodes.Object_100.geometry}
              material={materials['cover.033']}
            />
            <mesh
              ref={meshRef}
              geometry={nodes.Object_101.geometry}
              material={materials.cardboard}
            />
          </group>
          <group
            position={[-0.06, 0.16, -0.33]}
            rotation={[Math.PI / 2, 0.01, -Math.PI / 2]}
          >
            <mesh
              ref={meshRef}
              geometry={nodes.Object_103.geometry}
              material={materials['cover.034']}
            />
            <mesh
              ref={meshRef}
              geometry={nodes.Object_104.geometry}
              material={materials.cardboard}
            />
          </group>
          <group
            position={[-0.03, 0.16, -0.33]}
            rotation={[Math.PI / 2, 0, -Math.PI / 2]}
          >
            <mesh
              ref={meshRef}
              geometry={nodes.Object_106.geometry}
              material={materials['cover.035']}
            />
            <mesh
              ref={meshRef}
              geometry={nodes.Object_107.geometry}
              material={materials.cardboard}
            />
          </group>
          <group
            position={[0, 0.16, -0.33]}
            rotation={[Math.PI / 2, 0.04, -Math.PI / 2]}
          >
            <mesh
              ref={meshRef}
              geometry={nodes.Object_109.geometry}
              material={materials['cover.036']}
            />
            <mesh
              ref={meshRef}
              geometry={nodes.Object_110.geometry}
              material={materials.cardboard}
            />
          </group>
          <group
            position={[0.03, 0.16, -0.34]}
            rotation={[Math.PI / 2, 0, -Math.PI / 2]}
          >
            <mesh
              ref={meshRef}
              geometry={nodes.Object_112.geometry}
              material={materials['cover.037']}
            />
            <mesh
              ref={meshRef}
              geometry={nodes.Object_113.geometry}
              material={materials.cardboard}
            />
          </group>
          <group
            position={[0.06, 0.16, -0.34]}
            rotation={[Math.PI / 2, 0, -Math.PI / 2]}
          >
            <mesh
              ref={meshRef}
              geometry={nodes.Object_115.geometry}
              material={materials['cover.038']}
            />
            <mesh
              ref={meshRef}
              geometry={nodes.Object_116.geometry}
              material={materials.cardboard}
            />
          </group>
          <group
            position={[0.09, 0.16, -0.34]}
            rotation={[Math.PI / 2, 0, -Math.PI / 2]}
          >
            <mesh
              ref={meshRef}
              geometry={nodes.Object_118.geometry}
              material={materials['cover.039']}
            />
            <mesh
              ref={meshRef}
              geometry={nodes.Object_119.geometry}
              material={materials.cardboard}
            />
          </group>
          <group
            position={[0.13, 0.16, -0.33]}
            rotation={[Math.PI / 2, 0, -Math.PI / 2]}
          >
            <mesh
              ref={meshRef}
              geometry={nodes.Object_121.geometry}
              material={materials['cover.040']}
            />
            <mesh
              ref={meshRef}
              geometry={nodes.Object_122.geometry}
              material={materials.cardboard}
            />
          </group>
          <group
            position={[-0.15, 0.16, -0.34]}
            rotation={[Math.PI / 2, 0.02, -Math.PI / 2]}
          >
            <mesh
              ref={meshRef}
              geometry={nodes.Object_124.geometry}
              material={materials['cover.041']}
            />
            <mesh
              ref={meshRef}
              geometry={nodes.Object_125.geometry}
              material={materials.cardboard}
            />
          </group>
          <group
            position={[-0.13, 0.16, -0.33]}
            rotation={[Math.PI / 2, 0, -Math.PI / 2]}
          >
            <mesh
              ref={meshRef}
              geometry={nodes.Object_127.geometry}
              material={materials['cover.042']}
            />
            <mesh
              ref={meshRef}
              geometry={nodes.Object_128.geometry}
              material={materials.cardboard}
            />
          </group>
          <group
            position={[-0.1, 0.16, -0.34]}
            rotation={[Math.PI / 2, 0.04, -Math.PI / 2]}
          >
            <mesh
              ref={meshRef}
              geometry={nodes.Object_130.geometry}
              material={materials['cover.043']}
            />
            <mesh
              ref={meshRef}
              geometry={nodes.Object_131.geometry}
              material={materials.cardboard}
            />
          </group>
          <group
            position={[-0.06, 0.16, -0.33]}
            rotation={[Math.PI / 2, 0.02, -Math.PI / 2]}
          >
            <mesh
              ref={meshRef}
              geometry={nodes.Object_133.geometry}
              material={materials['cover.044']}
            />
            <mesh
              ref={meshRef}
              geometry={nodes.Object_134.geometry}
              material={materials.cardboard}
            />
          </group>
          <group
            position={[-0.04, 0.16, -0.33]}
            rotation={[Math.PI / 2, 0.03, -Math.PI / 2]}
          >
            <mesh
              ref={meshRef}
              geometry={nodes.Object_136.geometry}
              material={materials['cover.045']}
            />
            <mesh
              ref={meshRef}
              geometry={nodes.Object_137.geometry}
              material={materials.cardboard}
            />
          </group>
          <group
            position={[-0.01, 0.16, -0.33]}
            rotation={[Math.PI / 2, 0, -Math.PI / 2]}
          >
            <mesh
              ref={meshRef}
              geometry={nodes.Object_139.geometry}
              material={materials['cover.046']}
            />
            <mesh
              ref={meshRef}
              geometry={nodes.Object_140.geometry}
              material={materials.cardboard}
            />
          </group>
          <group
            position={[0.02, 0.16, -0.33]}
            rotation={[Math.PI / 2, 0.01, -Math.PI / 2]}
          >
            <mesh
              ref={meshRef}
              geometry={nodes.Object_142.geometry}
              material={materials['cover.047']}
            />
            <mesh
              ref={meshRef}
              geometry={nodes.Object_143.geometry}
              material={materials.cardboard}
            />
          </group>
          <group
            position={[0.05, 0.16, -0.34]}
            rotation={[Math.PI / 2, 0, -Math.PI / 2]}
          >
            <mesh
              ref={meshRef}
              geometry={nodes.Object_145.geometry}
              material={materials['cover.048']}
            />
            <mesh
              ref={meshRef}
              geometry={nodes.Object_146.geometry}
              material={materials.cardboard}
            />
          </group>
          <group
            position={[0.09, 0.16, -0.35]}
            rotation={[Math.PI / 2, 0, -Math.PI / 2]}
          >
            <mesh
              ref={meshRef}
              geometry={nodes.Object_148.geometry}
              material={materials['cover.049']}
            />
            <mesh
              ref={meshRef}
              geometry={nodes.Object_149.geometry}
              material={materials.cardboard}
            />
          </group>
          <group
            position={[0.12, 0.16, -0.34]}
            rotation={[Math.PI / 2, 0.05, -Math.PI / 2]}
          >
            <mesh
              ref={meshRef}
              geometry={nodes.Object_151.geometry}
              material={materials['cover.050']}
            />
            <mesh
              ref={meshRef}
              geometry={nodes.Object_152.geometry}
              material={materials.cardboard}
            />
          </group>
          <group position={[0, 0, 0.1]} rotation={[0, 0.44, 0]}>
            <mesh
              ref={meshRef}
              geometry={nodes.Object_154.geometry}
              material={materials['cover.051']}
            />
            <mesh
              ref={meshRef}
              geometry={nodes.Object_155.geometry}
              material={materials.cardboard}
            />
          </group>
          <group position={[0.19, 0, 0]} rotation={[0, -1.47, 0]}>
            <mesh
              ref={meshRef}
              geometry={nodes.Object_159.geometry}
              material={materials.label_front}
            />
            <mesh
              ref={meshRef}
              geometry={nodes.Object_160.geometry}
              material={materials.label_back}
            />
            <mesh
              ref={meshRef}
              geometry={nodes.Object_161.geometry}
              material={materials.label_side}
            />
            <mesh
              ref={meshRef}
              geometry={nodes.Object_157.geometry}
              material={materials.vinyl}
            />
          </group>
        </group>
      </group>
    </group>
  );
}

useGLTF.preload('/vinyls.gltf');
